## Assignment

In [11]:
import numpy as np
from PIL import Image
import os

In [12]:
rootDir = '.'
for dirName, subDirList,fileList in os.walk(rootDir):
    print("Found directory : %s" %dirName)

Found directory : .
Found directory : .\.git
Found directory : .\.git\hooks
Found directory : .\.git\info
Found directory : .\.git\logs
Found directory : .\.git\logs\refs
Found directory : .\.git\logs\refs\heads
Found directory : .\.git\logs\refs\remotes
Found directory : .\.git\logs\refs\remotes\origin
Found directory : .\.git\objects
Found directory : .\.git\objects\04
Found directory : .\.git\objects\06
Found directory : .\.git\objects\0b
Found directory : .\.git\objects\15
Found directory : .\.git\objects\1d
Found directory : .\.git\objects\20
Found directory : .\.git\objects\27
Found directory : .\.git\objects\33
Found directory : .\.git\objects\34
Found directory : .\.git\objects\39
Found directory : .\.git\objects\3c
Found directory : .\.git\objects\40
Found directory : .\.git\objects\4b
Found directory : .\.git\objects\5c
Found directory : .\.git\objects\61
Found directory : .\.git\objects\71
Found directory : .\.git\objects\7d
Found directory : .\.git\objects\7f
Found director

In [13]:
image_array = np.zeros([512,512,3])
print (image_array.ndim)
image_size = (512, 512)

3


In [22]:
for fname in fileList:
    if fname.endswith('.jpg'):
        print(fname)
        img = Image.open(fname)
        print(img)
        resized_img = img.resize((image_size),Image.BICUBIC)
        print(resized_img)
        image_array = np.append(image_array,resized_img)
        #image_array.concatenate(resized_img)
        print(image_array)
        

IM_1.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x188BF04B470>
<PIL.Image.Image image mode=RGB size=512x512 at 0x188BDEAC0F0>
[  0.   0.   0. ... 190. 163. 143.]
IM_10.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x188BF04B128>
<PIL.Image.Image image mode=RGB size=512x512 at 0x188BF04B470>
[  0.   0.   0. ... 183.  64.  39.]
IM_11.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x188BF04B390>
<PIL.Image.Image image mode=RGB size=512x512 at 0x188BEFED550>
[  0.   0.   0. ... 122. 118.  62.]
IM_12.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x188BF04B128>
<PIL.Image.Image image mode=RGB size=512x512 at 0x188BF04B390>
[ 0.  0.  0. ...  3. 36. 64.]
IM_13.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x188BF04B400>
<PIL.Image.Image image mode=RGB size=512x512 at 0x188BEFED550>
[  0.   0.   0. ... 138. 117.  46.]
IM_14.jpg
<PIL.JpegImagePlugin.JpegImageFile im